#
# -*- coding: utf-8 -*-
# Copyright 2023 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the awplus_premark_dscps module
"""


class Premark_dscpsArgs(object):  # pylint: disable=R0903
    """The arg spec for the awplus_premark_dscps module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
                     'options': {'class_new': {'choices': ['green', 'yellow', 'red'],
                                               'type': 'str'},
                                 'cos_new': {'type': 'int'},
                                 'dscp_in': {'required': True, 'type': 'int'},
                                 'dscp_new': {'type': 'int'}},
                                'type': 'list'},
                     'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
