#
# -*- coding: utf-8 -*-
# Copyright 2021 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the awplus_ntp module
"""


class NtpArgs(object):  # pylint: disable=R0903
    """The arg spec for the awplus_ntp module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        'config': {'options': {
            'authentication': {'elements': 'dict', 'options': {
                'auth_key': {'required': True, 'type': 'str'},
                'key_id': {'required': True, 'type': 'int'},
                'key_type': {'choices': ['md5', 'sha1'], 'required': True, 'type': 'str'}}, 'type': 'list'},
            'server': {'elements': 'str', 'type': 'list'},
            'source_int': {'type': 'str'}}, 'type': 'dict'},
        'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'], 'default': 'merged', 'type': 'str'}}  # pylint: disable=C0301
