authors:
  [
    "Cheng Yi Kok (@cyk19)",
    "Isaac Daly (@dalyIsaac)",
    "Jeremy Toth (@jtsource)",
    "Darryl Alang",
    "Tony van der Peet",
    "Ben Hoelker",
  ]
dependencies: {}
description: "Modules to support configuration of AlliedWare Plus devices."
documentation: "https://github.com/alliedtelesis/ansible_awplus"
homepage: "https://github.com/alliedtelesis/ansible_awplus"
issues: "https://github.com/alliedtelesis/ansible_awplus/issues"
license_file: LICENSE
name: awplus
namespace: alliedtelesis
readme: README.md
repository: "https://github.com/alliedtelesis/ansible_awplus"
tags: ["networking"]
build_ignore:
- .vscode
- .github
- .gitignore
version: 1.2.2
