#
# -*- coding: utf-8 -*-
# Copyright 2021 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the awplus_openflow module
"""


class OpenflowArgs(object):  # pylint: disable=R0903
    """The arg spec for the awplus_openflow module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'controllers': {'elements': 'dict',
                                        'options': {'address': {'type': 'str'},
                                                    'l4_port': {'type': 'int'},
                                                    'name': {'required': True,
                                                             'type': 'str'},
                                                    'protocol': {'choices': ['ssl',
                                                                             'tcp'],
                                                                 'type': 'str'}},
                                        'type': 'list'},
                        'datapath_id': {'type': 'str'},
                        'fail_mode': {'choices': ['secure',
                                                  'standalone',
                                                  'secure_nre'],
                                      'type': 'str'},
                        'inactivity_timer': {'type': 'int'},
                        'native_vlan': {'type': 'int'},
                        'peer_certificate': {'type': 'str'},
                        'ports': {'elements': 'str', 'type': 'list'},
                        'trustpoint': {'type': 'str'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
