#
# -*- coding: utf-8 -*-
# Copyright 2023 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the awplus_policy_maps module
"""


class Policy_mapsArgs(object):  # pylint: disable=R0903
    """The arg spec for the awplus_policy_maps module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
                     'options': {'classifiers': {'elements': 'dict',
                                                 'options': {'name': {'required': True,
                                                                      'type': 'str'},
                                                             'pbr_next_hop': {'type': 'str'},
                                                             'policer': {'options': {'action': {'choices': ['drop_red',
                                                                                                            'remark_transmit'],
                                                                                                'type': 'str'},
                                                                                     'cbs': {'type': 'int'},
                                                                                     'cir': {'type': 'int'},
                                                                                     'ebs': {'type': 'int'},
                                                                                     'pbs': {'type': 'int'},
                                                                                     'pir': {'type': 'int'},
                                                                                     'type': {'choices': ['single_rate',
                                                                                                          'twin_rate',
                                                                                                          'none'],
                                                                                              'type': 'str'}},
                                                                         'type': 'dict'},
                                                             'remark': {'options': {'apply': {'choices': ['internal',
                                                                                                          'external',
                                                                                                          'both',
                                                                                                          'none'],
                                                                                              'default': 'both',
                                                                                              'type': 'str'},
                                                                                    'new_cos': {'type': 'int'}},
                                                                        'type': 'dict'},
                                                             'remark_map': {'elements': 'dict',
                                                                            'options': {'class_in': {'choices': ['green',
                                                                                                                 'yellow',
                                                                                                                 'red'],
                                                                                                     'type': 'str'},
                                                                                        'new_class': {'choices': ['green',
                                                                                                                  'yellow',
                                                                                                                  'red',
                                                                                                                  'none'],
                                                                                                      'type': 'str'},
                                                                                        'new_dscp': {'type': 'int'}},
                                                                            'type': 'list'},
                                                             'storm_action': {'choices': ['port_disable',
                                                                                          'vlan_disable',
                                                                                          'link_down',
                                                                                          'none'],
                                                                              'type': 'str'},
                                                             'storm_downtime': {'default': 10,
                                                                                'type': 'int'},
                                                             'storm_protection': {'type': 'bool'},
                                                             'storm_rate': {'type': 'int'},
                                                             'storm_window': {'type': 'int'}},
                                                 'type': 'list'},
                                 'default_action': {'choices': ['permit',
                                                                'deny',
                                                                'copy_to_cpu',
                                                                'send_to_cpu',
                                                                'copy_to_mirror',
                                                                'send_to_mirror'],
                                                    'default': 'permit',
                                                    'type': 'str'},
                                 'description': {'type': 'str'},
                                 'name': {'required': True, 'type': 'str'},
                                 'trust_dscp': {'type': 'bool'}},
                                'type': 'list'},
                     'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
