#
# -*- coding: utf-8 -*-
# Copyright 2023 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the awplus_acl module
"""


class AclArgs(object):  # pylint: disable=R0903
    """The arg spec for the awplus_acl module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
            'options': {'acls': {'elements': 'dict',
                                 'options': {'aces': {'elements': 'dict',
                                                      'options': {'ICMP_type_number': {'type': 'int'},
                                                                  'ace_ID': {'type': 'int'},
                                                                  'action': {'choices': ['permit',
                                                                                         'deny']},
                                                                  'destination_addr': {'type': 'str'},
                                                                  'destination_port': {'type': 'int'},
                                                                  'protocols': {'choices': ['tcp',
                                                                                            'udp',
                                                                                            'icmp',
                                                                                            'ip']},
                                                                  'source_addr': {'type': 'str'},
                                                                  'source_port': {'type': 'int'}},
                                                      'type': 'list'},
                                             'acl_type': {'choices': ['extended',
                                                                      'standard',
                                                                      'hardware'],
                                                          'required': True},
                                             'name': {'required': True,
                                                      'type': 'str'}},
                                 'type': 'list'},
                        'afi': {'choices': ['IPv4', 'IPv6'], 'required': True}},
            'type': 'list'},
 'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
