#
# -*- coding: utf-8 -*-
# Copyright 2023 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the awplus_mlag module
"""


class MlagArgs(object):  # pylint: disable=R0903
    """The arg spec for the awplus_mlag module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'domains': {'elements': 'dict',
                                    'options': {'domain_id': {'required': True,
                                                              'type': 'int'},
                                                'keepalive_interval': {'default': 1,
                                                                       'type': 'int'},
                                                'peer_address': {'type': 'str'},
                                                'peer_link': {'type': 'str'},
                                                'session_timeout': {'default': 30,
                                                                    'type': 'int'},
                                                'source_address': {'type': 'str'}},
                                    'required': True,
                                    'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
