#
# -*- coding: utf-8 -*-
# Copyright 2021 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the awplus_bgp module
"""


class BgpArgs(object):  # pylint: disable=R0903
    """The arg spec for the awplus_bgp module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        'config': {'options': {
            'ipv4_address_family': {'elements': 'dict', 'options': {
                'neighbors': {'elements': 'dict', 'options': {
                    'activate': {'type': 'bool'},
                    'maximum_prefix': {'type': 'int'},
                    'neighbor': {'required': True, 'type': 'str'},
                    'next_hop_self': {'type': 'bool'},
                    'prefix_list_in': {'type': 'str'},
                    'prefix_list_out': {'type': 'str'},
                    'remote_as': {'required': True, 'type': 'int'},
                    'remove_private_as': {'type': 'bool'}}, 'type': 'list'},
                'networks': {'elements': 'dict', 'options': {
                    'backdoor': {'type': 'bool'},
                    'masklen': {'type': 'int'},
                    'prefix': {'required': True, 'type': 'str'},
                    'route_map': {'type': 'str'}}, 'type': 'list'},
                'redistribute': {'elements': 'dict', 'options': {
                    'protocol': {'choices': ['connected', 'isis', 'ospf', 'rip', 'static'], 'required': True, 'type': 'str'},
                    'route_map': {'type': 'str'}}, 'type': 'list'},
                'vrf': {'required': True, 'type': 'str'}}, 'type': 'list'},
            'l2vpn_address_family': {'options': {
                'vrfs': {'elements': 'dict', 'options': {
                    'vrf': {'required': True, 'type': 'str'},
                    'advertisements': {'elements': 'dict', 'options': {
                        'protocol': {'required': True, 'type': 'str'},
                        'route-map': {'type': 'str'}
                    }, 'type': 'list'}}, 'type': 'list'},
                'neighbors': {'elements': 'dict', 'options': {
                    'neighbor': {'required': True, 'type': 'str'},
                    'activate': {'type': 'bool'}}, 'type': 'list'},
                'advertise_all_vni': {'type': 'bool'}}, 'type': 'dict'},
            'bgp_as': {'required': True, 'type': 'int'},
            'log_neighbor_changes': {'type': 'bool'},
            'ebgp_requires_policy': {'type': 'bool'},
            'network_import_check': {'type': 'bool'},
            'neighbors': {'elements': 'dict', 'options': {
                'description': {'type': 'str'},
                'ebgp_multihop': {'type': 'int'},
                'enabled': {'type': 'bool'},
                'local_as': {'type': 'int'},
                'neighbor': {'required': True, 'type': 'str'},
                'password': {'type': 'str'},
                'peer_group': {'type': 'str'},
                'remote_as': {'required': True, 'type': 'int'},
                'timers': {'options': {
                    'connect': {'type': 'int'},
                    'holdtime': {'type': 'int'},
                    'keepalive': {'type': 'int'}}, 'type': 'dict'},
                'update_source': {'type': 'str'}}, 'type': 'list'},
            'networks': {'elements': 'dict', 'options': {
                'backdoor': {'type': 'bool'},
                'masklen': {'default': 32, 'type': 'int'},
                'prefix': {'required': True, 'type': 'str'},
                'route_map': {'type': 'str'}}, 'type': 'list'},
            'router_id': {'type': 'str'}}, 'type': 'dict'},
        'state': {'choices': ['merged', 'replaced', 'deleted'], 'default': 'merged', 'type': 'str'}}  # pylint: disable=C0301
