---
- hosts: all
  connection: network_cli
  collections:
    - alliedtelesis.awplus
  tasks:
    - name: testing out vrf module
      awplus_vrf:
        name: test_1
        interfaces:
          - vlan32
        state: present
