---
- hosts: all
  connection: network_cli
  collections:
    - alliedtelesis.awplus
  tasks:
    - name: Configure OSPF IPv6 router process id
      awplus_ospf_ipv6:
        router:
          process_id: 101
