#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2021 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for awplus_lacp_interfaces
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'network'
}

DOCUMENTATION = """
---
module: awplus_lacp_interfaces
short_description: 'Manages the LACP attributes of AlliedWare Plus interfaces'
description: 'This module manages LACP configuration on aggregated interfaces of AlliedWare Plus devices.'
version_added: 2.10.4
author: Darryl Alang
notes:
  - 'Tested against AlliedWare Plus AT-x930-28GTX'
options:
  config:
    description: A dictionary of interface options.
    type: list
    elements: dict
    suboptions:
      name:
        description:
          - Name of the interface to configure LACP on.
        type: str
        required: True
      port_priority:
        description:
          - Specify the LACP port priority. Valid values range 1-65535. Lower numbers correspond to higher priorities.
        type: int
      timeout:
        description:
          - Number of seconds before invalidating a received LACP data unit (DU).
          - Short timeout value is 1 second while long timeout value is 30 seconds.
        type: str
        choices:
        - long
        - short
  state:
    description:
    - The state the configuration should be left in
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    default: merged
"""
EXAMPLES = """
# Using merged

# Before state:
# -------------
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
#  switchport access vlan 99
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  channel-group 2 mode active
#  lacp port-priority 2
#  lacp timeout short
# !
# interface port1.0.3
#  switchport
#  switchport mode access
#  channel-group 3 mode active
# !
# interface port1.0.4-1.0.28
#  switchport
#  switchport mode access
# !

- name: Merge provided configuration with device configuration
  alliedtelesis.awplus.awplus_lacp_interfaces:
    config:
      - name: port1.0.3
        port_priority: 3
    state: merged

# After state:
# -------------
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
#  switchport access vlan 99
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  channel-group 2 mode active
#  lacp port-priority 2
#  lacp timeout short
# !
# interface port1.0.3
#  switchport
#  switchport mode access
#  channel-group 3 mode active
#  lacp port-priority 3
# !
# interface port1.0.4-1.0.28
#  switchport
#  switchport mode access
# !


# Using replaced

# Before state:
# -------------
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
#  switchport access vlan 99
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  channel-group 2 mode active
#  lacp port-priority 2
#  lacp timeout short
# !
# interface port1.0.3
#  switchport
#  switchport mode access
#  channel-group 3 mode active
#  lacp port-priority 3
# !
# interface port1.0.4-1.0.28
#  switchport
#  switchport mode access
# !

- name: Replace device configuration with provided configuration
  alliedtelesis.awplus.awplus_lacp_interfaces:
    config:
      - name: port1.0.3
        port_priority: 7
    state: replaced

# After state:
# -------------
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
#  switchport access vlan 99
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  channel-group 2 mode active
#  lacp port-priority 7
# !
# interface port1.0.3
#  switchport
#  switchport mode access
#  channel-group 3 mode active
#  lacp port-priority 3
# !
# interface port1.0.4-1.0.28
#  switchport
#  switchport mode access
# !


# Using overridden

# Before state:
# -------------
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
#  switchport access vlan 99
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  channel-group 2 mode active
#  lacp port-priority 2
#  lacp timeout short
# !
# interface port1.0.3
#  switchport
#  switchport mode access
#  channel-group 3 mode active
#  lacp port-priority 3
# !
# interface port1.0.4-1.0.28
#  switchport
#  switchport mode access
# !

- name: Override device configuration of all interfaces with provided configuration
  alliedtelesis.awplus.awplus_lacp_interfaces:
    config:
      - name: port1.0.3
        timeout: short

      - name: vlan2
        description: Overridden by Ansible Network
        mtu: 920
        enabled: True
    state: overridden

# -------------
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
#  switchport access vlan 99
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  channel-group 2 mode active
# !
# interface port1.0.3
#  switchport
#  switchport mode access
#  channel-group 3 mode active
#  lacp timeout short
# !
# interface port1.0.4-1.0.28
#  switchport
#  switchport mode access
# !


# Using deleted

# Before state:
# -------------
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
#  switchport access vlan 99
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  channel-group 2 mode active
#  lacp port-priority 2
#  lacp timeout short
# !
# interface port1.0.3
#  switchport
#  switchport mode access
#  channel-group 3 mode active
#  lacp port-priority 3
# !
# interface port1.0.4-1.0.28
#  switchport
#  switchport mode access
# !

- name: Delete module attributes of given interfaces (Note that this won't delete the interface itself)
  alliedtelesis.awplus.awplus_lacp_interfaces:
    config:
      - name: port1.0.2
    state: deleted

# After state:
# -------------
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
#  switchport access vlan 99
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  channel-group 2 mode active
# !
# interface port1.0.3
#  switchport
#  switchport mode access
#  channel-group 3 mode active
#  lacp port-priority 3
# !
# interface port1.0.4-1.0.28
#  switchport
#  switchport mode access
# !

# Using deleted without any config passed
# NOTE: This will delete all of configured resource module attributes from each configured interface

# Before state:
# -------------
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
#  switchport access vlan 99
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  channel-group 2 mode active
#  lacp port-priority 2
#  lacp timeout short
# !
# interface port1.0.3
#  switchport
#  switchport mode access
#  channel-group 3 mode active
#  lacp port-priority 3
# !
# interface port1.0.4-1.0.28
#  switchport
#  switchport mode access
# !

- name: Delete module attributes of all interfaces
  alliedtelesis.awplus.awplus_lacp_interfaces:
    state: deleted

# After state:
# -------------
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
#  switchport access vlan 99
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  channel-group 2 mode active
# !
# interface port1.0.3
#  switchport
#  switchport mode access
#  channel-group 3 mode active
# !
# interface port1.0.4-1.0.28
#  switchport
#  switchport mode access
# !


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['interface port1.0.2', 'lacp timeout short']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.argspec.lacp_interfaces.lacp_interfaces import Lacp_interfacesArgs
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.config.lacp_interfaces.lacp_interfaces import Lacp_interfaces


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    required_if = [
        ("state", "merged", ("config",)),
        ("state", "replaced", ("config",)),
        ("state", "overridden", ("config",)),
    ]
    module = AnsibleModule(argument_spec=Lacp_interfacesArgs.argument_spec,
                           required_if=required_if,
                           supports_check_mode=True)

    result = Lacp_interfaces(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
