#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for awplus_l3_interfaces
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'network'
}

DOCUMENTATION = """
---
module: awplus_l3_interfaces
short_description: 'Manages attributes of AlliedWare Plus Layer 3 interfaces.'
description: 'Manages attributes of AlliedWare Plus Layer 3 interfaces'
version_added: 2.10.4
author: Ansible Network Engineer
notes:
  - 'Tested against AlliedWare Plus main-20210107-1'
options:
  config:
    description: The provided configuration.
    type: list
    elements: dict
    suboptions:
      name:
        description: The full name of the Layer 3 interfaces.
        type: str
        required: true
      ipv4:
        description:
        - The primary IPv4 address on the interface in the format <ip-addr/prefix-length>.
        type: list
        elements: dict
        suboptions:
          address:
            description:
            - Sets the IPv4 address for the interface.
            type: str
            required: true
          secondary:
            description:
              - Adds additional IP addresses on this interface. A primary address on the interface must
                be set before configuring a secondary address.
            type: bool
          dhcp_client:
            description:
              - The ID of the interface you are activating the DHCP client on.
            type: int
          dhcp_hostname:
            description:
              - hostname for the DHCP client on this interface. Typically this name is provided by the ISP.
            type: str
      ipv6:
        description:
          - Specifies the IPv6 address to be set. The IPv6 address uses the format X:X::X:X/Prefix-Length.
            The prefix-length is usually set between 0 and 64.
        type: list
        elements: dict
        suboptions:
          address:
            description:
              - Configures the IPv6 address for interface
            type: str
            required: true
  state:
    description:
    - The state the configuration should be left in
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    default: merged
"""
EXAMPLES = """
# Using merged
#
# Before state:
# -------------
#
# awplus#show running-config interface
# ...
# interface vlan2
#  ip address dhcp client-id vlan2 hostname test.com
# !
# interface vlan3
#  ipv6 address 2003:db8::ffdf/64
# !
# interface vlan4
#  ip address dhcp
# !
# interface vlan5
#  ipv6 address 2001:db8::a2/64
#  ipv6 address dhcp
# !
# interface vlan99
#  ip address 10.38.55.3/27
# !

- name: Merge l3 interfaces configuration with provided configuration
  alliedtelesis.awplus.awplus_l3_interfaces:
    config:
      - name: vlan99
        ipv4:
          - address: 192.168.0.2/24
            secondary: True
    state: merged

# After state:
# ------------
#
# awplus#show running-config interface
# ...
# interface vlan2
#  ip address dhcp client-id vlan2 hostname test.com
# !
# interface vlan3
#  ipv6 address 2003:db8::ffdf/64
# !
# interface vlan4
#  ip address dhcp
# !
# interface vlan5
#  ipv6 address 2001:db8::a2/64
#  ipv6 address dhcp
# !
# interface vlan99
#  ip address 10.38.55.3/27
#  ip address 192.168.0.2/24 secondary
# !


# Using replaced
#
# Before state:
# -------------
#
# awplus#show running-config interface
# ...
# interface vlan2
#  ip address dhcp client-id vlan2 hostname test.com
# !
# interface vlan3
#  ipv6 address 2003:db8::ffdf/64
# !
# interface vlan4
#  ip address dhcp
# !
# interface vlan5
#  ipv6 address 2001:db8::a2/64
#  ipv6 address dhcp
# !
# interface vlan99
#  ip address 10.38.55.3/27
# !

- name: Merge listed l3 interfaces configuration with provided configuration
  alliedtelesis.awplus.awplus_l3_interfaces:
    config:
      - name: vlan5
        ipv4:
          - address: 7.6.13.97/24
    state: replaced

# After state:
# -------------
#
# awplus#show running-config interface
# ...
# interface vlan2
#  ip address dhcp client-id vlan2 hostname test.com
# !
# interface vlan3
#  ipv6 address 2003:db8::ffdf/64
# !
# interface vlan4
#  ip address dhcp
# !
# interface vlan5
#  ip address 7.6.13.97/24
# !
# interface vlan99
#  ip address 10.38.55.3/27
# !


# Using overridden
#
# Before state:
# -------------
#
# awplus#show running-config interface
# ...
# interface vlan2
#  description vlan2
#  ip address dhcp client-id vlan2 hostname test.com
# !
# interface vlan3
#  description vlan3
#  ipv6 address 2003:db8::ffdf/64
# !
# interface vlan4
#  description vlan4
#  ip address dhcp
# !
# interface vlan5
#  description vlan5
#  ipv6 address 2001:db8::a2/64
#  ipv6 address dhcp
# !
# interface vlan99
#  ip address 10.38.55.3/27
# !

- name: Override l3 interfaces configuration with provided configuration
  alliedtelesis.awplus.awplus_l3_interfaces:
    config:
      - name: vlan99
        ipv4:
          - address: 10.38.55.3/27
    state: overridden

# After state:
# ------------
#
# awplus#show running-config interface
# ...
# interface vlan2
#  description vlan2
# !
# interface vlan3
#  description vlan3
# !
# interface vlan4
#  description vlan4
# !
# interface vlan5
#  description vlan5
# !
# interface vlan99
#  ip address 10.38.55.3/27
# !


# Using deleted
#
# Before state:
# -------------
#
# awplus#show running-config interface
# ...
# interface vlan2
#  ip address dhcp client-id vlan2 hostname test.com
# !
# interface vlan3
#  ipv6 address 2003:db8::ffdf/64
# !
# interface vlan4
#  ip address dhcp
# !
# interface vlan5
#  description vlan5
#  ipv6 address 2001:db8::a2/64
#  ipv6 address dhcp
# !
# interface vlan99
#  ip address 10.38.55.3/27
# !

- name: Delete attributes of given interface
  alliedtelesis.awplus.awplus_l3_interfaces:
    config:
      - name: vlan5
    state: deleted

# After state:
# ------------
#
# awplus#show running-config interface
# ...
# interface vlan2
#  ip address dhcp client-id vlan2 hostname test.com
# !
# interface vlan3
#  ipv6 address 2003:db8::ffdf/64
# !
# interface vlan4
#  ip address dhcp
# !
# interface vlan5
#  description vlan5
# !
# interface vlan99
#  ip address 10.38.55.3/27
# !


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['interface vlan5',
          'ipv6 address dhcp']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.argspec.l3_interfaces.l3_interfaces import L3_interfacesArgs
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.config.l3_interfaces.l3_interfaces import L3_interfaces


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=L3_interfacesArgs.argument_spec,
                           supports_check_mode=True)

    result = L3_interfaces(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
