#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for awplus_lacp
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'network'
}

DOCUMENTATION = """
---
module: awplus_lacp
short_description: 'Manage Global Link Aggregation Control Protocol (LACP) on AlliedWare Plus devices.'
description: 'Manages the global attributes of AlliedWare Plus Link Aggregation Control Protocol (LACP)'
version_added: 2.10.4
author: Ansible Network Engineer
notes:
  - 'Tested against AlliedWare Plus x930 main-20210107-1'
options:
  config:
    description: The provided configuration.
    type: dict
    suboptions:
      system:
        description: This option sets the default system parameters for LACP.
        type: dict
        suboptions:
          priority:
            description:
            - LACP system priority. Lower numerical values have higher priorities. Integer range 1-65535.
            type: int
            required: true
  state:
    description:
    - The state the configuration should be left in
    type: str
    choices:
    - merged
    - deleted
    default: merged
"""
EXAMPLES = """
# Using merged
#
# Before state:
# -------------
#
# awplus#show lacp sys-id
# System Priority: 0x8000 (32768)
# MAC Address: 001a.eb94.27bb

- name: Merge provided configuration with device configuration
  alliedtelesis.awplus.awplus_lacp:
    config:
      system:
        priority: 123
    state: merged

# After state:
# ------------
#
# aw1#show lacp sys-id
# System Priority: 0x007b (123)
# MAC Address: 001a.eb94.27bb


# Using deleted
#
# Before state:
# -------------
#
# aw1#show lacp sys-id
# System Priority: 0x007b (123)
# MAC Address: 001a.eb94.27bb

- name: Delete global lacp attibute
  alliedtelesis.awplus.awplus_lacp:
    state: deleted

# After state:
# -------------
#
# aw1#show lacp sys-id
# System Priority: 0x8000 (32768)
# MAC Address: 001a.eb94.27bb


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['lacp system-priority 6700']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.argspec.lacp.lacp import LacpArgs
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.config.lacp.lacp import Lacp


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=LacpArgs.argument_spec,
                           supports_check_mode=True)

    result = Lacp(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
