#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2023 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for awplus_mlag_interfaces
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'network'
}

DOCUMENTATION = """
---
module: awplus_mlag
version_added: 1.4.0
short_description: Manage the mlag attributes for interfaces on AlliedWare Plus devices
description:
    - This module provides declarative management of mlag attributes
      for interfaces awplus devices. It provides options to configure 
      host system parameters or remove those parameters from the 
      device's active configuration.
author:
  - Ryan Scofield
notes:
  - Tested against x530
options:
  config:
    description: Configuration of the MLAG interfaces module.
    type: list
    elements: dict
    suboptions:
      name:
        description:
          - An aggregate port to configure MLAG domains for.
        required: True
        type: str
      domain_id: 
        description:
          - The id of the MLAG domain.
        type: int
  state:
    description:
      - The state the configuration should be left in, defaults to merged
    choices:
      - merged
      - overridden
      - deleted
    default: merged
    type: str
"""
EXAMPLES = """
# Using merged

# Before state:
# -------------
# awplus(config)#
# interface po4
#  mlag 10

- name: Merge config
  alliedtelesis.awplus.awplus_mlag:
    config:
      - name: po5
        domain_id: 10
    state: merged

# After state:
# -----------
# awplus(config)#
# interface po4
#  mlag 10
# !
# interface po5
#  mlag 10


# Using overridden

# Before state:
# -------------
# awplus(config)#
# interface po4
#  mlag 10

- name: Override config
  alliedtelesis.awplus.awplus_mlag:
    config:
      - name: po5
        domain_id: 10
    state: overridden

# After state:
# -----------
# awplus(config)#
# interface po5
#  mlag 10


# Using deleted

# Before state:
# -------------
# awplus(config)#
# interface po4
#  mlag 10
# !
# interface po5
#  mlag 10

- name: Delete config
  alliedtelesis.awplus.awplus_mlag:
    config:
      - name: po4
      - name: po5
    state: deleted

# After state:
# -----------
# awplus(config)#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['interface po5', 'mlag 10']

"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.argspec.mlag_interfaces.mlag_interfaces import Mlag_interfacesArgs
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.config.mlag_interfaces.mlag_interfaces import Mlag_interfaces


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Mlag_interfacesArgs.argument_spec,
                           supports_check_mode=True)

    result = Mlag_interfaces(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
