#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2023 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for awplus_static_route
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'network'
}

DOCUMENTATION = """
---
module: awplus_static_route
version_added: 2.13.6
short_description: Manage static routes on Allied Telesis AlliedWare Plus devices.
description: This module manages the properties of static routes on Allied Telesis AlliedWare Plus devices.
author: Ben Hoelker
notes:
- Tested against AlliedWare Plus on SBx908NG.
options:
  config:
    description:
      - A list of static route configurations.
    type: list
    elements: dict
    suboptions:
      afi:
        description:
          - specifies whether to use an IPv4 or IPv6 static route.
        choices:
          - IPv4
          - IPv6
        required: true
      address:
        description:
          - The IPv4 address of the destination subnet.
          - permitted formats.
          - address subnet_mask
          - address/prefix_length
        type: str
        required: true
      vrf:
        description:
          - configures a vrf to use in a static route.
        type: str
      source_address:
        description:
          - Sets the source prefix, used for SADR.
          - Accepts the format X:X::/prefix_length
          - Only use for IPv6 static routes
        type: str
      next_hop:
        description:
          - An interface/next hop, which connects the device to the network.
          - Accepts a valid IPv4/IPv6 address or VLAN/VID.
          - Enter null to add a blackhole route to the switch.
        type: str
      admin_distance:
        description:
          - The administrative distance for the static route.
          - Accepts inputs in the range 1-255, where 1 is the highest priority
        type: int
      description:
        description:
          - The description to use for the static route
        type: str
  state:
    description:
    - The state the configuration should be left in
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    default: merged
"""
EXAMPLES = """
# Using Merged

# Before state:
# -------------
#
# awplus#show running-config | include route
# ip route 172.121.1.0/24 vlan1 100 description a description

- name: create a new static route
  awplus_static_route:
    config:
      - afi: IPv4
        address: 192.164.12.0/24
        next_hop: vlan1
        description: static route description
        admin_distance: 100
    operation: merged

# After state:
# -------------
#
# awplus#show running-config | include route
# ip route 172.121.1.0/24 vlan1 100 description a description
# ip route 192.164.12.0/24 vlan1 100 description static route description


# Using Replaced

# Before state:
# -------------
#
# awplus#show running-config | include route
# ip route 172.121.1.0/24 vlan1 100 description a description
# ip route 192.164.12.0/24 vlan1 100 description static route description

- name: Replace a static_route
  awplus_static_route
    config:
      - afi: IPv4
        address: 192.164.12.0/24
        next_hop: vlan1
        admin_distance: 100

# After state:
# -------------
#
awplus#show running-config | include route
ip route 172.121.1.0/24 vlan1 100 description a description
ip route 192.164.12.0/24 vlan1 100


# Using Overridden

# Before state:
# -------------
#
awplus#show running-config | include route
ip route 172.121.1.0/24 vlan1 100 description a description
ip route 192.164.12.0/24 vlan1 100 description static route description

- name: Override the config with a new static route
  awplus_static_route:
    config:
      - afi: IPv4
        address: 168.154.3.0/24
        next_hop: vlan2
        source_address:
        description: new description
        admin_distance: 25
    operation: overridden

# After state:
# -------------
#
# awplus#show running-config | include route
# ip route 168.154.3.0/24 vlan2 25 description new description


# Using Deleted

# Before state:
# -------------
#
# awplus#show running-config | include route
# ip route 172.121.1.0/24 vlan1 100 description a description
# ip route 192.164.12.0/24 vlan1 100 description static route description
# ip route 192.164.12.0/24 vlan2 100 description another static route description

- name: Delete a specific static route
  awplus_static_route:
    config:
      - afi: IPv4
        address: 192.164.12.0/24
        next_hop: vlan1
    operation: deleted

# After state:
# -------------
#
# awplus#show running-config | include route
# ip route 172.121.1.0/24 vlan1 100 description a description
# ip route 192.164.12.0/24 vlan2 100 description another static route description


# Using Deleted

# Before state:
# -------------
#
# awplus#show running-config | include route
# ip route 172.121.1.0/24 vlan1 100 description a description
# ip route 192.164.12.0/24 vlan2 100 description another static route description
# ip route 192.164.12.0/24 vlan1 100 description static route description
# ip route 192.164.12.0/24 vlan4 101

- name: Delete all static routes using address
  awplus_policy_maps:
    config:
      - afi: IPv4
        address: 192.164.12.0/24
    operation: deleted

# After state:
# -------------
#
# awplus#show running-config | include route
# ip route 172.121.1.0/24 vlan1 100 description a description


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.argspec.static_route.static_route import Static_routeArgs
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.config.static_route.static_route import Static_route


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Static_routeArgs.argument_spec,
                           supports_check_mode=True)

    result = Static_route(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
