#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2021 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for awplus_openflow
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'network'
}

DOCUMENTATION = """
---
module: awplus_openflow
version_added: 2.9
short_description: Manage OpenFlow configuration on Allied Telesis AlliedWare Plus devices.
description: This module manages properties of the OpenFlow feature on Allied Telesis AlliedWare Plus devices.
author: Tony van der Peet
notes:
- Tested against AlliedWare Plus on SBx908NG.
options:
  config:
    description:
    - Configuration for OpenFlow.
    type: dict
    suboptions:
      controllers:
        description:
        - List of Openflow controllers this switch will attempt to connect to.
        type: list
        elements: dict
        suboptions:
          name:
            description:
            - Name of Openflow controller. If not specified a name will be generated.
            type: str
            required: True
          protocol:
            description:
            - Protocol type to communicate with the OpenFlow controller.
            type: str
            choices:
            - ssl
            - tcp
          address:
            description:
            - The IPv4 address of the Controller
            type: str
          l4_port:
            description:
            - Port number used to communicate with the OpenFlow controller.
            type: int
      ports:
        description:
        - List of data plane ports enabled for Openflow.
        type: list
        elements: str
      native_vlan:
        description:
        - Native VLAN for data plane ports. All Openflow ports must have this VLAN as the native VLAN.
        type: int
      fail_mode:
        description:
        - Operation mode for the switch when the Controller connection fails or no Controllers are defined.
        type: str
        choices:
        - secure
        - standalone
        - secure_nre
      inactivity_timer:
        description:
        - Value in seconds of the timer used to detect inactivity between the switch and controller.
        type: int
      datapath_id:
        description:
        - The datapath ID (1-16 Hex digits) for this Openflow switch.
        type: str
      trustpoint:
        description:
        - The trustpoint used to authenticate SSL connections.
        type: str
      peer_certificate:
        description:
        - Optional peer certificate, either a file name, or the value "bootstrap" to indicate bootstrap mode.
        type: str
  state:
    description:
    - The state the configuration should be left in.
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    default: merged
"""
EXAMPLES = """
# Using Merged

# Before state:
# -------------
#
# awplus#sh open config
# a7d12d80-70f4-4bef-bb9e-a588eb38abab
#     Bridge of0
#         Controller "tcp:192.168.100.100:6654"
#             other_config: {aux_id="0", name=Gauge}
#         fail_mode: secure
#         datapath_type: system
#         Port of0
#             Interface of0
#                 type: internal
#         Port port1.6.1
#             Interface port1.6.1
#                 type: system
#                 options: {ifindex="5601", mtu="1500", native_vlan="4090"}
#         Port port1.6.2
#             Interface port1.6.2
#                 type: system
#                 options: {ifindex="5602", mtu="1500", native_vlan="4090"}
#         Port port1.6.3
#             Interface port1.6.3
#                 type: system
#                 options: {ifindex="5603", mtu="1500", native_vlan="4090"}
#         Port port1.6.4
#             Interface port1.6.4
#                 type: system
#                 options: {ifindex="5604", mtu="1500", native_vlan="4090"}

- name: Merge a new controller into the Openflow configuration
  awplus_openflow:
    config:
      controllers:
        - name: Faucet
          protocol: tcp
          address: 192.168.100.100
          l4_port: 6653
    state: merged

# After state:
# -------------
#
# awplus#sh open config
# a7d12d80-70f4-4bef-bb9e-a588eb38abab
#     Bridge of0
#         Controller "tcp:192.168.100.100:6653"
#             other_config: {aux_id="0", name=Faucet}
#         Controller "tcp:192.168.100.100:6654"
#             other_config: {aux_id="0", name=Gauge}
#         fail_mode: secure
#         datapath_type: system
#         Port of0
#             Interface of0
#                 type: internal
#         Port port1.6.1
#             Interface port1.6.1
#                 type: system
#                 options: {ifindex="5601", mtu="1500", native_vlan="4090"}
#         Port port1.6.2
#             Interface port1.6.2
#                 type: system
#                 options: {ifindex="5602", mtu="1500", native_vlan="4090"}
#         Port port1.6.3
#             Interface port1.6.3
#                 type: system
#                 options: {ifindex="5603", mtu="1500", native_vlan="4090"}
#         Port port1.6.4
#             Interface port1.6.4
#                 type: system
#                 options: {ifindex="5604", mtu="1500", native_vlan="4090"}


# Using Replaced

# Before state:
# -------------
#
# awplus#sh open config
# a7d12d80-70f4-4bef-bb9e-a588eb38abab
#     Bridge of0
#         Controller "tcp:192.168.100.100:6653"
#             other_config: {aux_id="0", name=Faucet}
#         Controller "tcp:192.168.100.100:6654"
#             other_config: {aux_id="0", name=Gauge}
#         fail_mode: secure
#         datapath_type: system
#         Port of0
#             Interface of0
#                 type: internal
#         Port port1.6.1
#             Interface port1.6.1
#                 type: system
#                 options: {ifindex="5601", mtu="1500", native_vlan="4090"}
#         Port port1.6.2
#             Interface port1.6.2
#                 type: system
#                 options: {ifindex="5602", mtu="1500", native_vlan="4090"}
#         Port port1.6.3
#             Interface port1.6.3
#                 type: system
#                 options: {ifindex="5603", mtu="1500", native_vlan="4090"}
#         Port port1.6.4
#             Interface port1.6.4
#                 type: system
#                 options: {ifindex="5604", mtu="1500", native_vlan="4090"}

- name: Override controller configuration
  awplus_openflow:
    config:
      controllers:
        - name: Faucet
          protocol: tcp
          address: 192.168.100.100
          l4_port: 6653
    state: overridden

# After state:
# -------------
#
# awplus#sh open config
# a7d12d80-70f4-4bef-bb9e-a588eb38abab
#     Bridge of0
#         Controller "tcp:192.168.100.100:6653"
#             other_config: {aux_id="0", name=Faucet}
#         fail_mode: secure
#         datapath_type: system
#         Port of0
#             Interface of0
#                 type: internal
#         Port port1.6.1
#             Interface port1.6.1
#                 type: system
#                 options: {ifindex="5601", mtu="1500", native_vlan="4090"}
#         Port port1.6.2
#             Interface port1.6.2
#                 type: system
#                 options: {ifindex="5602", mtu="1500", native_vlan="4090"}
#         Port port1.6.3
#             Interface port1.6.3
#                 type: system
#                 options: {ifindex="5603", mtu="1500", native_vlan="4090"}
#         Port port1.6.4
#             Interface port1.6.4
#                 type: system
#                 options: {ifindex="5604", mtu="1500", native_vlan="4090"}


# Using Overridden

# Before state:
# -------------
#
# awplus#sh open config
# a7d12d80-70f4-4bef-bb9e-a588eb38abab
#     Bridge of0
#         Controller "tcp:192.168.100.100:6653"
#             other_config: {aux_id="0", name=Faucet}
#         Controller "tcp:192.168.100.100:6654"
#             other_config: {aux_id="0", name=Gauge}
#         fail_mode: secure
#         datapath_type: system
#         Port of0
#             Interface of0
#                 type: internal
#         Port port1.6.1
#             Interface port1.6.1
#                 type: system
#                 options: {ifindex="5601", mtu="1500", native_vlan="4090"}
#         Port port1.6.2
#             Interface port1.6.2
#                 type: system
#                 options: {ifindex="5602", mtu="1500", native_vlan="4090"}
#         Port port1.6.3
#             Interface port1.6.3
#                 type: system
#                 options: {ifindex="5603", mtu="1500", native_vlan="4090"}
#         Port port1.6.4
#             Interface port1.6.4
#                 type: system
#                 options: {ifindex="5604", mtu="1500", native_vlan="4090"}

- name: Override controller configuration
  awplus_openflow:
    config:
      controllers:
        - name: Faucet
          protocol: tcp
          address: 192.168.100.100
          l4_port: 6653
    state: overridden

# After state:
# -------------
#
# awplus#sh open config
# a7d12d80-70f4-4bef-bb9e-a588eb38abab
#     Bridge of0
#         Controller "tcp:192.168.100.100:6653"
#             other_config: {aux_id="0", name=Faucet}
#         fail_mode: secure
#         datapath_type: system
#         Port of0
#             Interface of0
#                 type: internal


# Using Deleted

# Before state:
# -------------
#
# awplus#sh open config
# a7d12d80-70f4-4bef-bb9e-a588eb38abab
#     Bridge of0
#         Controller "tcp:192.168.100.100:6653"
#             other_config: {aux_id="0", name=Faucet}
#         Controller "tcp:192.168.100.100:6654"
#             other_config: {aux_id="0", name=Gauge}
#         fail_mode: secure
#         datapath_type: system
#         Port of0
#             Interface of0
#                 type: internal
#         Port port1.6.1
#             Interface port1.6.1
#                 type: system
#                 options: {ifindex="5601", mtu="1500", native_vlan="4090"}
#         Port port1.6.2
#             Interface port1.6.2
#                 type: system
#                 options: {ifindex="5602", mtu="1500", native_vlan="4090"}
#         Port port1.6.3
#             Interface port1.6.3
#                 type: system
#                 options: {ifindex="5603", mtu="1500", native_vlan="4090"}
#         Port port1.6.4
#             Interface port1.6.4
#                 type: system
#                 options: {ifindex="5604", mtu="1500", native_vlan="4090"}

- name: Delete an Openflow controller
  awplus_openflow:
    config:
      controllers:
        - name: Faucet
    state: deleted

# After state:
# -------------
#
# awplus#sh open config
# a7d12d80-70f4-4bef-bb9e-a588eb38abab
#     Bridge of0
#         Controller "tcp:192.168.100.100:6654"
#             other_config: {aux_id="0", name=Gauge}
#         fail_mode: secure
#         datapath_type: system
#         Port of0
#             Interface of0
#                 type: internal
#         Port port1.6.1
#             Interface port1.6.1
#                 type: system
#                 options: {ifindex="5601", mtu="1500", native_vlan="4090"}
#         Port port1.6.2
#             Interface port1.6.2
#                 type: system
#                 options: {ifindex="5602", mtu="1500", native_vlan="4090"}
#         Port port1.6.3
#             Interface port1.6.3
#                 type: system
#                 options: {ifindex="5603", mtu="1500", native_vlan="4090"}
#         Port port1.6.4
#             Interface port1.6.4
#                 type: system
#                 options: {ifindex="5604", mtu="1500", native_vlan="4090"}


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.argspec.openflow.openflow import OpenflowArgs
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.config.openflow.openflow import Openflow


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=OpenflowArgs.argument_spec,
                           supports_check_mode=True)

    result = Openflow(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
