#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2021 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for awplus_vlans
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'network'
}

DOCUMENTATION = """
---
module: awplus_vlans
short_description: 'Manages VLAN configuration of AlliedWare Plus devices'
description: 'This module manages VLAN configuration of AlliedWare Plus devices.'
version_added: 1.1.0
author: Darryl Alang
notes:
  - 'Tested against AlliedWare Plus AT-x930-28GTX'
options:
  config:
    description: The provided configuration.
    type: list
    elements: dict
    suboptions:
      name:
        description:
          - The ASCII name of the VLAN. Maximum length is 32 characters.
        type: str
      vlan_id:
        description:
          - The ID of the VLAN to enable or disable, in the range 1-4094.
        type: int
        required: True
      state:
        description:
          - Operational state of the VLAN
        type: str
        choices:
          - active
          - suspend
  state:
    description:
    - The state the configuration should be left in
    - Note that I(state=deleted) and I(state=overridden) will not remove the default vlan 1.
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    default: merged
"""
EXAMPLES = """
# Using merged

# Before state:
# -------------
# awplus#show vlan all
# VLAN ID  Name            Type    State   Member ports
#                                          (u)-Untagged, (t)-Tagged
# ======= ================ ======= ======= ====================================
# 1       default          STATIC  ACTIVE  port1.0.1(u) port1.0.2(u) port1.0.3(u)
#                                          port1.0.4(u)

- name: Merge provided configuation to device configuation
  alliedtelesis.awplus.awplus_vlans:
    config:
      - vlan_id: 2
        name: MONO
      - vlan_id: 3
        state: suspend
    state: merged

# After state:
# -------------
# awplus#show vlan all
# VLAN ID  Name            Type    State   Member ports
#                                          (u)-Untagged, (t)-Tagged
# ======= ================ ======= ======= ====================================
# 1       default          STATIC  ACTIVE  port1.0.1(u) port1.0.2(u) port1.0.3(u)
#                                          port1.0.4(u)
# 2       MONO             STATIC  ACTIVE
# 3       VLAN0003         STATIC  SUSPEND


# Using replaced

# Before state:
# -------------
# awplus#show vlan all
# VLAN ID  Name            Type    State   Member ports
#                                          (u)-Untagged, (t)-Tagged
# ======= ================ ======= ======= ====================================
# 1       default          STATIC  ACTIVE  port1.0.1(u) port1.0.2(u) port1.0.3(u)
#                                          port1.0.4(u)
# 2       MONO             STATIC  ACTIVE
# 3       VLAN0003         STATIC  SUSPEND

- name: Replace device configuation with provided configuation
  alliedtelesis.awplus.awplus_vlans:
    config:
      - vlan_id: 2
        state: suspend
    state: replaced

# After state:
# -------------
# awplus#show vlan all
# VLAN ID  Name            Type    State   Member ports
#                                          (u)-Untagged, (t)-Tagged
# ======= ================ ======= ======= ====================================
# 1       default          STATIC  ACTIVE  port1.0.1(u) port1.0.2(u) port1.0.3(u)
#                                          port1.0.4(u)
# 2       VLAN0002         STATIC  SUSPEND
# 3       VLAN0003         STATIC  SUSPEND


# Using overridden

# Before state:
# -------------
# awplus#show vlan all
# VLAN ID  Name            Type    State   Member ports
#                                          (u)-Untagged, (t)-Tagged
# ======= ================ ======= ======= ====================================
# 1       default          STATIC  ACTIVE  port1.0.3(u) port1.0.4(u)
# 2       MONO             STATIC  ACTIVE  port1.0.2(u)
# 3       VLAN0003         STATIC  SUSPEND port1.0.3(t)
# 4       VLAN0004         STATIC  ACTIVE  port1.0.3(t)
# 5       VLAN0005         STATIC  ACTIVE
# 6       VLAN0006         STATIC  ACTIVE
# 99      VLAN0099         STATIC  ACTIVE  port1.0.1(u)

- name: Override device configuation with provided configuation
  alliedtelesis.awplus.awplus_vlans:
    config:
      - vlan_id: 2
        state: suspend
        name: moonchild
    state: overridden

# After state:
# -------------
# awplus#show vlan all
# VLAN ID  Name            Type    State   Member ports
#                                          (u)-Untagged, (t)-Tagged
# ======= ================ ======= ======= ====================================
# 1       default          STATIC  ACTIVE  port1.0.1(u) port1.0.2(u) port1.0.3(u)
#                                          port1.0.4(u)
# 2       moonchild        STATIC  SUSPEND


# Using deleted

# Before state:
# -------------
# awplus#show vlan all
# VLAN ID  Name            Type    State   Member ports
#                                          (u)-Untagged, (t)-Tagged
# ======= ================ ======= ======= ====================================
# 1       default          STATIC  ACTIVE  port1.0.3(u) port1.0.4(u)
# 2       MONO             STATIC  ACTIVE  port1.0.2(u)
# 3       VLAN0003         STATIC  SUSPEND port1.0.3(t)
# 4       VLAN0004         STATIC  ACTIVE  port1.0.3(t)
# 5       VLAN0005         STATIC  ACTIVE
# 6       VLAN0006         STATIC  ACTIVE
# 99      VLAN0099         STATIC  ACTIVE  port1.0.1(u)


- name: Delete all vlans
  alliedtelesis.awplus.awplus_vlans:
    config:
      - vlan_id: 5
      - vlan_id: 6
    state: deleted

# After state:
# -------------
# awplus#show vlan all
# VLAN ID  Name            Type    State   Member ports
#                                          (u)-Untagged, (t)-Tagged
# ======= ================ ======= ======= ====================================
# 1       default          STATIC  ACTIVE  port1.0.3(u) port1.0.4(u)
# 2       MONO             STATIC  ACTIVE  port1.0.2(u)
# 3       VLAN0003         STATIC  SUSPEND port1.0.3(t)
# 4       VLAN0004         STATIC  ACTIVE  port1.0.3(t)
# 99      VLAN0099         STATIC  ACTIVE  port1.0.1(u)


# Using Deleted without any config passed

# Before state:
# -------------
# awplus#show vlan all
# VLAN ID  Name            Type    State   Member ports
#                                          (u)-Untagged, (t)-Tagged
# ======= ================ ======= ======= ====================================
# 1       default          STATIC  ACTIVE  port1.0.3(u) port1.0.4(u)
# 2       MONO             STATIC  ACTIVE  port1.0.2(u)
# 3       VLAN0003         STATIC  SUSPEND port1.0.3(t)
# 4       VLAN0004         STATIC  ACTIVE  port1.0.3(t)
# 5       VLAN0005         STATIC  ACTIVE
# 6       VLAN0006         STATIC  ACTIVE
# 99      VLAN0099         STATIC  ACTIVE  port1.0.1(u)

- name: Delete all vlans
  alliedtelesis.awplus.awplus_vlans:
    state: deleted

# After state:
# -------------
# awplus#show vlan all
# VLAN ID  Name            Type    State   Member ports
#                                          (u)-Untagged, (t)-Tagged
# ======= ================ ======= ======= ====================================
# 1       default          STATIC  ACTIVE  port1.0.1(u) port1.0.2(u) port1.0.3(u)
#                                          port1.0.4(u)


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['vlan 4 name airplane state disable']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.argspec.vlans.vlans import VlansArgs
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.config.vlans.vlans import Vlans


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    required_if = [
        ("state", "merged", ("config",)),
        ("state", "replaced", ("config",)),
        ("state", "overridden", ("config",)),
    ]
    module = AnsibleModule(argument_spec=VlansArgs.argument_spec,
                           required_if=required_if,
                           supports_check_mode=True)

    result = Vlans(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
