#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2023 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for awplus_mlag
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'network'
}

DOCUMENTATION = """
---
module: awplus_mlag
version_added: 2.19
short_description: Manage the mlag attributes on AlliedWare Plus devices
description:
    - This module provides declarative management of mlag attributes
      on awplus devices. It provides options to configure host system
      parameters or remove those parameters from the device's active
      configuration.
author:
  - Ryan Scofield
notes:
  - Tested against x530
options:
  config:
    description: Configuration of the MLAG module.
    type: dict
    suboptions:
      domains:
        description:
          - The MLAG domains to configure.
        type: list
        elements: dict
        required: True
        suboptions:
          domain_id:
            description:
              - The id of the domain.
            type: int
            required: True
          peer_link:
            description:
              - The peer-link interface for this MLAG domain.
            type: str
          source_address:
            description:
              - The MLAG domain source ip address.
            type: str
          peer_address:
            description:
              - The MLAG domain peer ip address.
            type: str
          keepalive_interval:
            description:
              - Interval at which keepalive messages are exchanged between peers.
            default: 1
            type: int
          session_timeout:
            description:
              - Seconds waited without recieving keep alive messages from a peer
                before assuming the peer is down.
            default: 30
            type: int
  state:
    description:
      - The state the configuration should be left in, defaults to merged
    choices:
      - merged
      - replaced
      - overridden
      - deleted
    default: merged
    type: str
"""
EXAMPLES = """
# Using replaced

# Before state:
# -------------
# awplus(config)#
# mlag domain 10
#  source-address 1.1.1.1
#  peer-address 255.255.255.255
#  keepalive-interval 20

- name: Merge config
  alliedtelesis.awplus.awplus_mlag:
    config:
      domains:
        - domain_id: 10
          source_address: 2.2.2.2
          peer_link: port1.0.1
    state: merged

# After state:
# -----------
# awplus(config)#
# mlag domain 10
#  source-address 2.2.2.2
#  peer-address 255.255.255.255
#  peer-link port1.0.1
#  keepalive-interval 20


# Using replaced

# Before state:
# -------------
# awplus(config)#
# mlag domain 10
#  source-address 1.1.1.1
#  peer-address 255.255.255.255
#  keepalive-interval 20

- name: Replace config
  alliedtelesis.awplus.awplus_mlag:
    config:
      domains:
        - domain_id: 10
          source_address: 2.2.2.2
          peer_link: port1.0.1
    state: replaced

# After state:
# -----------
# awplus(config)#
# mlag domain 10
#  source-address 2.2.2.2
#  peer-link port1.0.1


# Using replaced

# Before state:
# -------------
# awplus(config)#
# mlag domain 10
#  source-address 1.1.1.1
#  peer-address 255.255.255.255
#  keepalive-interval 20

- name: Replace config
  alliedtelesis.awplus.awplus_mlag:
    config:
      domains:
        - domain_id: 10
          source_address: 2.2.2.2
          peer_link: port1.0.1
    state: replaced

# After state:
# -----------
# awplus(config)#
# mlag domain 10
#  source-address 2.2.2.2
#  peer-link port1.0.1


# Using replaced

# Before state:
# -------------
# awplus(config)#
# mlag domain 10
#  source-address 1.1.1.1
#  peer-address 255.255.255.255
#  keepalive-interval 20

- name: Delete config
  alliedtelesis.awplus.awplus_mlag:
    config:
      domains:
        - domain_id: 10
    state: deleted

# After state:
# -----------
# awplus(config)#
# !
# !


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['mlag domain 1', 'source-address 1.1.1.1', 'peer-address 1.1.1.2', 'session-timeout 60']

"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.argspec.mlag.mlag import MlagArgs
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.config.mlag.mlag import Mlag


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=MlagArgs.argument_spec,
                           supports_check_mode=True)

    result = Mlag(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
