#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2023 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for awplus_policy_interfaces
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'network'
}

DOCUMENTATION = """
---
module: awplus_policy_interfaces
version_added: 2.13.6
short_description: 'Manages the configuration of policies on interfaces'
description: 'This module manages the configuration of interfaces on Alliedware Plus devices with respect to QoS policies.'
author:
  - Tony van der Peet
notes:
  - Tested against AlliedWare Plus on SBx908NG.
options:
  config:
    description:
      - Configuration of the policies on interfaces module.
    type: list
    elements: dict
    suboptions:
      int_name:
        description:
          - Name of the interface. Valid intefaces are "port..." and "sa...".
        type: str
        required: True
      policy_name:
        description:
          - The QoS policy for this interface.
        type: str
  state:
    description:
      - The state the configuration should be left in, defaults to merged
    choices:
      - merged
      - replaced
      - overridden
      - deleted
    default: merged
"""
EXAMPLES = """
# Using Merged

# Before state:
# -------------
#
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  service-policy input pm1
# !
# interface port1.0.3-1.0.52
#  switchport
#  switchport mode access
# !

- name: Merged Example
      awplus_policy_interfaces:
        config:
          - int_name: port1.0.1
            policy_name: pm1
        state: merged

# After state:
# -----------
#
# awplus#show running-config interface
# interface port1.0.1-1.0.2
#  switchport
#  switchport mode access
#  service-policy input pm1
# !
# interface port1.0.3-1.0.52
#  switchport
#  switchport mode access
# !


# Using Replaced

# Before state:
# -------------
#
# awplus#show running-config interface
# interface port1.0.1-1.0.2
#  switchport
#  switchport mode access
#  service-policy input pm1
# !
# interface port1.0.3-1.0.52
#  switchport
#  switchport mode access
# !

- name: Replaced example
  awplus_policy_interfaces:
    config:
      - int_name: port1.0.1
        policy_name: pm2
    state: replaced

# After state:
# -----------
#
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
#  service-policy input pm2
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  service-policy input pm1
# !
# interface port1.0.3-1.0.52
#  switchport
#  switchport mode access
# !


# Using Overridden

# Before state:
# -------------
#
# awplus#show running-config interface
# interface port1.0.1-1.0.2
#  switchport
#  switchport mode access
#  service-policy input pm1
# !
# interface port1.0.3-1.0.52
#  switchport
#  switchport mode access
# !

- name: Overidden Example
      awplus_policy_interfaces:
        config:
          - int_name: port1.0.3
            policy_name: pm3
        state: overridden

# After state:
# -----------
#
# awplus#show running-config interface
# interface port1.0.1-1.0.2
#  switchport
#  switchport mode access
# !
# interface port1.0.3
#  switchport
#  switchport mode access
#  service-policy input pm3
# !
# interface port1.0.4-1.0.52
#  switchport
#  switchport mode access
# !


# Using Deleted

# Before state:
# -------------
#
# awplus#show running-config interface
# interface port1.0.1-1.0.2
#  switchport
#  switchport mode access
#  service-policy input pm1
# !
# interface port1.0.3-1.0.52
#  switchport
#  switchport mode access
# !

- name: Deleted Example
      awplus_policy_interfaces:
        config:
          - int_name: port1.0.1
        state: deleted

# After state:
# -----------
#
# awplus#show running-config interface
# interface port1.0.1
#  switchport
#  switchport mode access
# !
# interface port1.0.2
#  switchport
#  switchport mode access
#  service-policy input pm1
# !
# interface port1.0.3-1.0.52
#  switchport
#  switchport mode access
# !


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['interface port1.6.1', 'service-policy input pm1']

"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.argspec.policy_interfaces.policy_interfaces import Policy_interfacesArgs
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.config.policy_interfaces.policy_interfaces import Policy_interfaces


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Policy_interfacesArgs.argument_spec,
                           supports_check_mode=True)

    result = Policy_interfaces(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
