#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2023 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for awplus_vxlan
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'network'
}

DOCUMENTATION = """
---
module: awplus_vxlan
version_added: 1.3.0
short_description: Manage the vxlan attributes on AlliedWare Plus devices
description:
    - This module provides declarative management of dynamic vxlan
      attributes on awplus devices. It provides options to configure
      host system parameters or remove those parameters from the
      device's active configuration. This is mostly targetted towards
      the setting up and tearing down of VXLAN tunnels.
author:
  - Ryan Scofield
notes:
  - Tested against x530
options:
  config:
    description: Configuration of dynamic VXLAN module.
    type: dict
    suboptions:
      l2_vnis:
        description: Map existing VLAN ID to an L2VNI.
        type: list
        elements: dict
        suboptions:
          vlan:
            description: ID of the VLAN, in the range 1-4094.
            type: int
          vni:
            description: ID of the L2VNI, in the range 1-16777215.
            type: int
  state:
    description:
      - The state the configuration should be left in, defaults to merged
    choices:
      - merged
      - replaced
      - overridden
      - deleted
    default: merged
    type: str
"""
EXAMPLES = """
# Using merged

# Before state:
# -----------
# awplus#show running-config
# nvo vxlan
#  host-reachability-protocol evpn-bgp
#  source-interface lo
#  map-access vlan 10 vni 200

- name: Merge config
  alliedtelesis.awplus.awplus_vxlan:
    config:
      l2_vnis:
        - vlan: 11
          vni: 300
    state: merged

# After state:
# -----------
# awplus#show running-config
# nvo vxlan
#  host-reachability-protocol evpn-bgp
#  source-interface lo
#  map-access vlan 10 vni 200
#  map-access vlan 11 vni 300


# Using replaced

# Before state:
# -----------
# awplus#show running-config
# nvo vxlan
#  host-reachability-protocol evpn-bgp
#  source-interface lo
#  map-access vlan 10 vni 200

- name: Replace config
  alliedtelesis.awplus.awplus_vxlan:
    config:
      l2_vnis:
        - vlan: 11
          vni: 300
    state: replaced

# After state:
# -----------
# awplus#show running-config
# nvo vxlan
#  host-reachability-protocol evpn-bgp
#  source-interface lo
#  map-access vlan 10 vni 200
#  map-access vlan 11 vni 300


# Using overridden

# Before state:
# -----------
# awplus#show running-config
# nvo vxlan
#  host-reachability-protocol evpn-bgp
#  source-interface lo
#  map-access vlan 10 vni 200

- name: Override config
  alliedtelesis.awplus.awplus_vxlan:
    config:
      l2_vnis:
        - vlan: 11
          vni: 300
    state: overridden

# After state:
# -----------
# awplus#show running-config
# nvo vxlan
#  host-reachability-protocol evpn-bgp
#  source-interface lo
#  map-access vlan 11 vni 300


# Using deleted

# Before state:
# -----------
# awplus#show running-config
# nvo vxlan
#  host-reachability-protocol evpn-bgp
#  source-interface lo
#  map-access vlan 11 vni 200

- name: Delete config
  alliedtelesis.awplus.awplus_vxlan:
    config:
      l2_vnis:
        - vlan: 11
    state: deleted

# After state:
# -----------
# awplus#show running-config
# nvo vxlan
#  host-reachability-protocol evpn-bgp
#  source-interface lo


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['nvo vxlan', 'host-reachability-protocol evpn-bgp', 'map-access vlan 10 vni 12']

"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.argspec.vxlan.vxlan import VxlanArgs
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.config.vxlan.vxlan import Vxlan


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=VxlanArgs.argument_spec,
                           supports_check_mode=True)

    result = Vxlan(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
